<?php

function tester_form_alter(&$form, &$form_state, &$form_id) {
    switch($form_id) {
      case 'user_login_block':
        $form['name']['#title'] = null;

      case 'user_login_block':
        $form['pass']['#title'] = null;

      case 'comment_node_plotoer_form':
        $form['author']['_author']['#title'] = 'hdhdhdhdhdhdhdhdhdhdhdh';

      case 'comment_node_active_form':
        $form;

        break;

        // print out main id of form --->  $form_id  <-----
     }
    //  print '<pre>';
    //  print_r($form);
    //  print '</pre>';

    }
